const { existsSync, writeFileSync, mkdirSync } = require("fs");
const path = require("path");

const ENV_SPECS = {
  dev: { ip: "0.0.0.0", extraHosts: ["host.docker.internal:host-gateway"] },
  qa: { ip: "10.130.180.33", extraHosts: ["qadockerde.udaya-tech.com:10.130.180.33", "host.docker.internal:host-gateway"] },
  prod: { ip: "10.130.180.29", extraHosts: ["host.docker.internal:host-gateway"] },
  local: { ip: "0.0.0.0", extraHosts: ["host.docker.internal:host-gateway"] },
};

// * Compose template generator (fully compatible with Watchtower)
const generateComposeYml = (config, envName, spec, forceMode) => {
  const isLocalBuild = envName === "local" || envName === "dev";
  const imageName = `${config.registryPrefix}${config.name}:${envName}`;

  // * Watchtower requires 'image:' property to monitor container
  let imageOrBuild = "";
  if (forceMode === "build" || (!forceMode && isLocalBuild)) {
    // * Hybrid: specifies both image tag AND local build context for Watchtower compatibility
    imageOrBuild = `    image: ${imageName}\n    build:\n      context: .\n      dockerfile: Dockerfile`;
  } else {
    imageOrBuild = `    image: ${imageName}`;
  }

  return `# * ${envName.toUpperCase()} Server Docker Compose (Auto-generated by ut-build)
name: ${config.name}

services:
  api:
${imageOrBuild}
    container_name: ${config.name}-api
    restart: unless-stopped
    ports:
      - "${spec.ip}:${config.serverPort}:${config.serverPort}"
    volumes:
      - ${config.uploadDir}:/app/uploads
    environment:
      - FILE_UPLOAD_PATH=/app/uploads
      - JOOQ_CODEGEN_SKIP=true
    env_file:
      - .env
    extra_hosts:
${spec.extraHosts.map((h) => `      - "${h}"`).join("\n")}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  ${config.uploadDir}:
    name: ${config.uploadDir}
    external: true
`;
};

// * Generate all compose templates under templates/{env}/docker-compose.yml
const generateAllTemplates = (projectRoot, config) => {
  for (const [envName, spec] of Object.entries(ENV_SPECS)) {
    const dir = path.join(projectRoot, "templates", envName);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, "docker-compose.yml"), generateComposeYml(config, envName, spec));
  }
};

// * Generate standard production multi-stage Dockerfile
const generateDockerfile = (targetDir, config) => {
  const content = `# Stage 1: Extract layers using minimal JRE 25
FROM eclipse-temurin:25-jre-alpine AS builder
WORKDIR /builder
ARG JAR_FILE=app.jar
COPY \${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

# Stage 2: Minimal production container
FROM eclipse-temurin:25-jre-alpine
RUN apk add --no-cache tzdata curl
ENV TZ="Asia/Phnom_Penh"
WORKDIR /app

RUN addgroup -S spring && adduser -S spring -G spring
RUN mkdir -p /app/uploads && chown -R spring:spring /app/uploads
USER spring:spring

COPY --from=builder /builder/dependencies/ ./
COPY --from=builder /builder/spring-boot-loader/ ./
COPY --from=builder /builder/snapshot-dependencies/ ./
COPY --from=builder /builder/application/ ./

ENV JAVA_OPTS="-XX:+UseContainerSupport \\
  -XX:MaxRAMPercentage=60.0 \\
  -XX:MaxMetaspaceSize=160m \\
  -XX:CompressedClassSpaceSize=64m \\
  -XX:ReservedCodeCacheSize=64m \\
  -XX:+UseSerialGC \\
  -Xss256k \\
  -Djava.security.egd=file:/dev/./urandom \\
  -XX:+ExitOnOutOfMemoryError"

EXPOSE ${config.serverPort}
ENTRYPOINT ["sh", "-c", "java \$JAVA_OPTS org.springframework.boot.loader.launch.JarLauncher"]
`;
  writeFileSync(path.join(targetDir, "Dockerfile"), content);
};

module.exports = { ENV_SPECS, generateComposeYml, generateAllTemplates, generateDockerfile };
